[package]
name = "sched"
version = "0.1.0"
authors = ["crides <zhuhaoqing@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.32"
chrono = { version = "0.4.13", features = ["serde"] }
# clap = "*"
mongodb = { version = "1.1.0-beta", default-features = false, features = ["sync"] }
bson = "1.1.0-beta"
rlua_serde = { version = "0.4.0", path = "../rlua_serde" }
rlua = { version = "0.17.0", path = "../rlua" }
rustyline = "6.2.0"
serde = "1.0.115"
serde_derive = "1.0.115"
lazy_static = "1.4.0"
dirs = "3.0.1"
either = "1.6.0"
regex = "1.3.9"
